services:
  - type: web
    name: trans-app
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: gunicorn backend.main:app -k uvicorn.workers.UvicornWorker
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: MONGO_URL
        sync: false
    autoDeploy: false
